### PR TITLE
Create Text element with key

### PR DESCRIPTION
**Pull request by sospedra**
Avoids React warning about keys in iterator arrays https://facebook.github.io/react/tutorial/tutorial.html#keys

### CODE REVIEW

**Comment by Matthewnie** [comment]
Tested it out, solves the warning, thanks!

**Comment by sospedra** [comment]
@CharlesMangwa 👀

**Comment by jackkinsella** [comment]
looking fwd to when this gets merged into master. On Expo at least, I'm getting a minimum of three warnings on every page with Markdown. 

Sometimes I wish the React framework would be a tiny little bit less pushy about this sort of stuff.

**Comment by sospedra** [comment]
@CharlesMangwa Please, I don't want to fork... Again, another `react-native` lib 😞

**Comment by sunkibaek** [comment]
@CharlesMangwa We also need this to be merged, too. Thanks.

**Pull request merged**
