### PR TITLE
Ability to add own rules

### PR DESCRIPTION
**Pull request by oziks**
In my current project, I need to measure the image dimensions for applying a ratio. The best way to do this is to add `rules` prop.

### CODE REVIEW

**Comment by CharlesMangwa** [comment]
Hi @oziks! That's a nice idea, it should help a bunch of people: thanks! I'll take some time this we to merge it and add some features.

**Comment by oziks** [comment]
Thanks @CharlesMangwa!

**Comment by imspikey** [comment]
Sorry but I still didn't understand how to use a custom rule.
Can you show a sample please?

**Comment by oziks** [comment]
Hey @imspikey !

This package uses a list of rules to map a markdown element to a React Native rendering. 

You can find the initial list of rules in this file https://github.com/CharlesMangwa/react-native-simple-markdown/blob/next/src/rules.js

And to understand how to use the rules property in your component to override with your own rendering, I'll let you look at the project's readme.

Do not hesitate to ask for more details

**Pull request merged**
