### PR TITLE
Adding Whitelist/Blacklist capabilities

### PR DESCRIPTION
**Pull request by dvisco**
- added in white and blacklisting postProcessor for rules to strip out unwanted default styles
- kept in necessary default paragraph and text styling options

### CODE REVIEW

**Comment by CharlesMangwa** [comment]
Hi @dvisco! If I get it right, this PR aims to avoid styles rules overwriting between `paragraph` and `text`?

**Comment by dvisco** [comment]
Hi @CharlesMangwa, the goal of the PR is to allow for easy removal of unwanted styling options without having to pass in rule objects that have their `react` key implemented/dummied to ignore those styling options.

For example:
```jsx
            <Markdown styles={ styles }
                whitelist={['link', 'url']}>
              { description }
            </Markdown>
```
Will only apply the default styles for `link` and `url`. Previously I'd of had to pass in a `rules` prop that contained a key for all the styles I didn't want and reimplement their styling output.

I put in a safety piece that doesn't allow you to remove `paragraph` and `text` stylings accidentally, you can still override them if you choose. Without those options the underlying `simple-markdown` component will throw an error for having unmatched styles.

**Comment by CharlesMangwa** [comment]
Hello @dvisco! Thanks for your detailed explanation. Very nice idea, it should help a bunch of people indeed!

**Comment by dvisco** [comment]
@CharlesMangwa thanks for the wonderful repo!

**Pull request merged**
